tekubu/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
  get "about" => "home#about", as: "about"

  # resources :books, :only => [:index, :show]
  resources :books, :only => [:show]
  # resources :events

  # get 'tags/:tag', to: 'events#index', as: :tag

  # get 'home#show'
end

tekubu/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

tekubu/app/models/book.rb
class Book < ApplicationRecord
  # belongs_to :article, class_name: "Evnet", foreign_key: "event_id"
  # has_many :posts, dependent: :destroy
  has_many :events
  # has_many :voters, through: :posts, source: :member
  acts_as_taggable_on :dictionary
  acts_as_taggable
end

tekubu/app/models/event.rb
class Event < ApplicationRecord
	# belongs_to :book, class_name: "Book", foreign_key: "book_id"
  # counter_culture :book
  acts_as_taggable_on :dictionary
  acts_as_taggable

  class << self
    def status_text(status)
      I18n.t("activerecord.attributes.entry.status_#{status}")
    end

    def status_options
      STATUS_VALUES.map { |status| [status_text(status), status] }
    end

    def sidebar_entries(member, num = 5)
      readable_for(member).order(posted_at: :desc).limit(num)
    end
  end

end

tekubu/app/models/model.rb
class Tag < ApplicationRecord
	# belongs_to :book, class_name: "Book", foreign_key: "book_id"
  # counter_culture :book
  has_many :taggings
end

tekubu/app/models/post.rb
class Post < ApplicationRecord
	belongs_to :book, optional: true
end

tekubu/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include MetaTaggable
end

tekubu/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    if params[:tag]
      # tagのハッシュがあった時
      # tagged_withでタグ「:tag」でタグごとにフィルター
      @books = Book.tagged_with(params[:tag])
    else
      @books = Book.all
      @tags = Book.all_tags
      @tagpost = Book.tags_on(:dictionary)
      # @bobby = Book.tagged_with(@tagpost.name)

      p "tagpost=========================================="
      # p @tagpost
      p "bobby=========================================="
      # p @bobby
      p "//bobby=========================================="
    end
  end

  def show
    @book = Book.find(params[:id])
    @tags = Book.all_tags
    prepare_meta_tags(
      title: @book.title,
      description: @book.title + "の紹介ページ。Qiitaの投稿記事に紹介されている本の情報をまとめて紹介するサイト「Tekubu」（テクブ）。プログラミングに関する知識を記録・共有するためのサービスQiitaに投稿している記事数をカウントしておすすめの本をご紹介します。",
      og: {
      title: @book.title + " | Qiitaの投稿記事に紹介されている本の情報をまとめて紹介するサイト｜Tekubu（テクブ）",
        description: @book.title + "の紹介ページ。Qiitaの投稿記事に紹介されている本の情報をまとめて紹介するサイト「Tekubu」（テクブ）。プログラミングに関する知識を記録・共有するためのサービスQiitaに投稿している記事数をカウントしておすすめの本をご紹介します。",
        image: @book.image
      },
      twitter: {
      title: @book.title + " | Qiitaの投稿記事に紹介されている本の情報をまとめて紹介するサイト｜Tekubu（テクブ）",
        description: @book.title + "の紹介ページ。Qiitaの投稿記事に紹介されている本の情報をまとめて紹介するサイト「Tekubu」（テクブ）。プログラミングに関する知識を記録・共有するためのサービスQiitaに投稿している記事数をカウントしておすすめの本をご紹介します。",
        image: @book.image
      }
      )
  end

  # 新規登録フォーム
  def new
    @book = Book.new(created_at: Time.current)
  end

  # 編集
  def edit
    @book = books.find(params[:id])
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to @book, notice: "記事を作成しました。"
    else
      render "new"
    end
  end

  def update
    @book = books.find(params[:id])
    if @book.save
      redirect_to @book, notice: "記事を更新しました。"
    else
      render "edit"
    end
  end

  def destroy
    @book = books.find(params[:id])
    @book.destroy
    redirect_to :books, notice: "記事を削除しました。"
  end

  def search
    if params[:keyword].present?
      #　デバックログ出力するために記述
      Amazon::Ecs.debug = true

      # Amazon::Ecs::Responceオブジェクトの取得
      books = Amazon::Ecs.item_search(
        params[:keyword],
        search_index:  'Books',
        dataType: 'script',
        response_group: 'ItemAttributes, Images',
        country:  'jp',
        power: "Not kindle"
      )

      # 本のタイトル,画像URL, 詳細ページURLの取得
      @books = []
      books.items.each do |item|
        book = Book.new(
          item.get('ItemAttributes/Title'),
          item.get('LargeImage/URL'),
          item.get('DetailPageURL'),
        )
        @books << book
      end
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :event_id , :url, :url_hash, :content, :post_created, :post_updated, :created_at,:dictionary_list)
  end
end

tekubu/app/controllers/concerns/meta_taggable.rb
module MetaTaggable
  extend ActiveSupport::Concern

  include ActionView::Helpers::AssetUrlHelper

  included do
    before_action :prepare_meta_tags
  end

  private

  def prepare_meta_tags(options = {})
    base = t('meta_tags.base')

    site = base[:site]
    description = base[:description]
    title = t("meta_tags.titles.#{controller_name}.#{action_name}", default: '')
    image = image_url('ogp.png')
    image = options[:image].presence || image_url('ogp.png')

    defaults = {
      site: site,
      title: title,
      description: description,
      keywords: base[:keywords],
      canonical: request.url,
      og: {
        url: request.url,
        title: title.presence || site,
        description: description,
        site_name: site,
        type: 'article',
        image: image
      },
      twitter: {
        card: 'summary_large_image',
        site: '@Tekubu_net',
        title: title.presence || site,
        description: description,
        image: image
      }
    }

    options.reverse_merge!(defaults)

    set_meta_tags(options)
  end
end

tekubu/app/controllers/events_controller.rb
class EventsController < ApplicationController

  # 新規登録フォーム
  def index
    if params[:tag]
      # tagのハッシュがあった時
      # tagged_withでタグ「:tag」でタグごとにフィルター
      @events = Event.tagged_with(params[:tag])
    else
      @events = Event.all
      @tags = Event.all_tags
      @tagpost = Event.tags_on(:dictionary)
      # @bobby = Event.tagged_with(@tagpost.name)

      p "tagpost=========================================="
      # p @tagpost
      p "bobby=========================================="
      # p @bobby
      p "//bobby=========================================="
    end
  end

  # 記事の詳細
  def show
    @event = Event.find(params[:id])
  end

  # 新規登録フォーム
  def new
    @event = Event.new(created_at: Time.current)
  end

  # 編集
  def edit
    @event = events.find(params[:id])
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to @event, notice: "記事を作成しました。"
    else
      render "new"
    end
  end

  def update
    @event = entries.find(params[:id])
    if @event.save
      redirect_to @event, notice: "記事を更新しました。"
    else
      render "edit"
    end
  end

  def destroy
    @event = entries.find(params[:id])
    @event.destroy
    redirect_to :events, notice: "記事を削除しました。"
  end

  private
  def event_params
    params.require(:event).permit(:title, :book_id , :url, :url_hash, :content, :post_created, :post_updated, :created_at,:dictionary_list)
  end

end

tekubu/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # @books = Book.all.includes(:events).paginate(page: params[:page], per_page: 10)
    # @books = Event.where.not(title: nil).includes(:events).paginate(page: params[:page], per_page: 10)
    # @tags = Event.all_tags
    @books = Book.where.not(title: nil).paginate(page: params[:page], per_page: 10)
    @tags = Book.all_tags
  end

  def show
    @book = Book.all.includes(:events).paginate(page: params[:page], per_page: 5)
  end

  def about
  end

  def not_found
    raise ActionController::RoutingError,
      "No route matches #{request.path.inspect}"
  end

  def bad_request
    raise ActionController::ParameterMissing, ""
  end

  def internal_server_error
    raise Exception
  end

end

tekubu/app/helpers/application_helper.rb
module ApplicationHelper
end

tekubu/app/helpers/events_helper.rb
module EventsHelper
end

tekubu/app/helpers/home_helper.rb
module HomeHelper
end

tekubu/app/views/books/_form.html.erb
<%= render "shared/errors", obj: @book %>

<div class="p-form">

    <div class="p-form__item">
      <div class="p-form__heading">
        <%= form.label :title %><span class="p-form__tag--important">必須</span>
      </div>
      <div class="p-form__date">
        <%= form.text_field :title%>
      </div>
    </div>

    <div class="p-form__item">
      <div class="p-form__heading">
        <%= form.label :event_id, 'event_id' %>
      </div>
      <div class="p-form__date">
        <%= form.text_field :event_id%>
      </div>
    </div>

    <div class="p-form__item">
      <div class="p-form__heading">
        <%= form.label :url, 'URL' %>
      </div>
      <div class="p-form__date">
        <%= form.text_field :url%>
      </div>
    </div>

    <div class="p-form__item">
      <div class="p-form__heading">
        <%= form.label :url_hash, 'url_hash' %>
      </div>
      <div class="p-form__date">
        <%= form.text_field :url_hash%>
      </div>
    </div>

    <div class="p-form__item">
      <div class="p-form__heading">
        <%= form.label :content %>
      </div>
      <div class="p-form__date">
        <%= form.text_area :content%>
      </div>
    </div>

    <div class="p-form__item">
      <div class="p-form__heading">
        <%= form.label :dictionary_list, 'イベント（投稿）をカンマ区切りで入力' %>
      </div>
      <div class="p-form__date">
        <%= form.text_field :dictionary_list%>
      </div>
    </div>

    <div class="p-form__item">
      <div class="p-form__heading">
        <%= form.label :post_created, for: "entry_posted_at_1i" %>
      </div>
      <div class="p-form__date">
        <%= form.datetime_select :post_created,
        start_year: 2000, end_year: Time.now.year + 1,
        use_month_numbers: true %>
      </div>
    </div>

    <div class="p-form__item">
      <div class="p-form__heading">
        <%= form.label :post_updated, for: "entry_posted_at_1i" %>
      </div>
      <div class="p-form__date">
        <%= form.datetime_select :post_updated,
        start_year: 2000, end_year: Time.now.year + 1,
        use_month_numbers: true %>
      </div>
    </div>

    <div class="p-form__item">
      <div class="p-form__heading">
        <%= form.label :created_at, for: "entry_posted_at_1i" %>
      </div>
      <div class="p-form__date">
        <%= form.datetime_select :created_at,
        start_year: 2000, end_year: Time.now.year + 1,
        use_month_numbers: true %>
      </div>
    </div>


  </div>

tekubu/app/views/books/edit.html.erb
<div class="u-text--center">
	<%= link_to "一覧に戻る", @book ,class: "c-textlink c-text--midium"%>
</div>

<%= form_for @book do |form| %>
<%= render "form", form: form %>
<div class="c-button"><%= form.submit %></div>
<% end %>

tekubu/app/views/books/index.html.erb
<div class="p-user">
	<div class="c-box p-user__item">
		#index
	</div>
</div>

tekubu/app/views/books/new.html.erb
<%= form_for @book do |form| %>
<%= render "form", form: form %>
<div class="c-button"><%= form.submit %></div>
<% end %>

tekubu/app/views/books/show.html.erb
<article class="p-article c-box">
	<div class="c-text--small c-box__id">POST ID&nbsp;/&nbsp;<%= @book.id %></div>
	<h2 class="c-box__title">
		<a href="<%= @book.detailpageurl %>" target="_blank"><%= @book.title %></a>
	</h2>
	<div class="c-box__content">
		<div class="c-box__image">
			<img src="<%= @book.image %>" alt="<%= @book.title %>">
		</div>
		<dl class="c-box__table">
			<% if @book.author.present? %>
			<dt class="c-box__table__headline">著者</dt>
			<dd class="c-box__table__data"><%= @book.author %></dd>
			<% end %>
			<% if @book.publicationdate.present? %>
			<dt class="c-box__table__headline">発売日</dt>
			<dd class="c-box__table__data"><%= @book.publicationdate %></dd>
			<% end %>
			<% if @book.language.present? %>
			<dt class="c-box__table__headline">言語</dt>
			<dd class="c-box__table__data"><%= @book.language %></dd>
			<% end %>
		</dl>
	</div>

	<% if @book.content.present? %>
	<p class="c-box__text">
		<%= simple_format(@book.content) %>
	</p>
	<% end %>

	<div class="c-button--sns js-sharebtn">
		<div class="c-button__sns__text"><i class="fab fa-twitter"></i> みんなにオススメする</div>
		<p class="c-button__sns__title"><%= @book.title %></p>
		<p class="c-button__sns__link"><%= url_for %></p>
	</div>

	<div class="c-box__quote">
		<h2 class="c-box__quote__title">掲載されているQiita記事（<%= @book.dictionary.count %> 件）</h2>
		<ul class="c-box__quote__list">

			<% @book.dictionary.each do |item| %>
			<li>
				<a href="<%= item.url %>" target="_blank"><%= item.name %></a>
			</li>
			<% end %>

		</ul>
	</div>

	<ul class="p-article__bottom c-text--midium">
		<li class="c-button--primary">
			<a href="<%= @book.detailpageurl %>" target="_blank">Amazon</a>
		</li>
		<li class="c-button--gray">
			<%= link_to "戻る", :back %>
		</li>
	</ul>

</article>

tekubu/app/views/events/_form.html.erb
<%= render "shared/errors", obj: @event %>

<div class="p-form">

    <div class="p-form__item">
      <div class="p-form__heading">
        <%= form.label :title %><span class="p-form__tag--important">必須</span>
      </div>
      <div class="p-form__date">
        <%= form.text_field :title%>
      </div>
    </div>

    <div class="p-form__item">
      <div class="p-form__heading">
        <%= form.label :book_id, 'book_id' %>
      </div>
      <div class="p-form__date">
        <%= form.text_field :book_id%>
      </div>
    </div>

    <div class="p-form__item">
      <div class="p-form__heading">
        <%= form.label :url, 'URL' %>
      </div>
      <div class="p-form__date">
        <%= form.text_field :url%>
      </div>
    </div>

    <div class="p-form__item">
      <div class="p-form__heading">
        <%= form.label :url_hash, 'url_hash' %>
      </div>
      <div class="p-form__date">
        <%= form.text_field :url_hash%>
      </div>
    </div>

    <div class="p-form__item">
      <div class="p-form__heading">
        <%= form.label :content %>
      </div>
      <div class="p-form__date">
        <%= form.text_area :content%>
      </div>
    </div>

    <div class="p-form__item">
      <div class="p-form__heading">
        <%= form.label :dictionary_list, 'タグ（本）をカンマ区切りで入力' %>
      </div>
      <div class="p-form__date">
        <%= form.text_field :dictionary_list%>
      </div>
    </div>


    <div class="p-form__item">
      <div class="p-form__heading">
        <%= form.label :post_created, for: "entry_posted_at_1i" %>
      </div>
      <div class="p-form__date">
        <%= form.datetime_select :post_created,
        start_year: 2000, end_year: Time.now.year + 1,
        use_month_numbers: true %>
      </div>
    </div>

    <div class="p-form__item">
      <div class="p-form__heading">
        <%= form.label :post_updated, for: "entry_posted_at_1i" %>
      </div>
      <div class="p-form__date">
        <%= form.datetime_select :post_updated,
        start_year: 2000, end_year: Time.now.year + 1,
        use_month_numbers: true %>
      </div>
    </div>

    <div class="p-form__item">
      <div class="p-form__heading">
        <%= form.label :created_at, for: "entry_posted_at_1i" %>
      </div>
      <div class="p-form__date">
        <%= form.datetime_select :created_at,
        start_year: 2000, end_year: Time.now.year + 1,
        use_month_numbers: true %>
      </div>
    </div>


  </div>

tekubu/app/views/events/dictionary.erb
っっっっっっっっ
<% tag_list.each do |tag| %>
  <span class="label label-primary"><%= tag %></span>
<% end %>

tekubu/app/views/events/edit.html.erb
<div class="u-text--center">
	<%= link_to "一覧に戻る", @entry ,class: "c-textlink c-text--midium"%>
</div>

<%= form_for @entry do |form| %>
<%= render "form", form: form %>
<div class="c-button"><%= form.submit %></div>
<% end %>

tekubu/app/views/events/index.html.erb
<% if @events.present? %>
<% @events.each do |event| %>
<article class="p-article c-talk--right">
	<p class="c-talk__name"><%= event.title %></p>

	<ul class="p-article__bottom c-text--midium">
		<li>
			<%= link_to "もっと読む", event %>
		</li>
	</ul>

<% event.dictionary_list.each do |item| %>
<span class="label label-primary"><%= item %></span><br>
<% end %>

<% event.dictionary_counts.each do |item| %>
<span class="label label-primary"><%= item.id %></span><br>
<% end %>


</article>
<br><br>
	<%# event.find_related_dictionary.each do |item| %>
	<!-- <p style="color:red;"><%#= item.title %></p> -->
	<%# end %>

<% end %>
<%#= will_paginate @events, :class => 'p-pager' %>
<% else %>
<p>記事がありません。</p>
<% end %>



<%#= @events.find_related_dictionary %>

<% @tags.each do |tag| %>
<li><%= tag.id %> <%= tag.name %></li>
<% end %>

<% @tagpost.each do |item| %>
<li><%= item.id %> <%= item.name %> カウント：<%= item.taggings_count %></li>
<% end %>

tekubu/app/views/events/new.html.erb
<%= form_for @event do |form| %>
<%= render "form", form: form %>
<div class="c-button"><%= form.submit %></div>
<% end %>

tekubu/app/views/events/show.html.erb
<article class="p-article c-talk--right">
	<%= @event.id %>
	<%= @event.title %>
	<%= @event.dictionary_list %>
	<%#= @event.find_related_dictionary %>

<%#= render 'dictionary', event: @event.find_related_dictionary %>

<h2><%= "Tag:#{params[:tag_name]}" %></h2>
<%= @event %>
</article>

tekubu/app/views/home/about.html.erb
<% set_meta_tags title: "Tekubu（テクブ）について",
description: "Tekubu（テクブ）は、エンジニアにおすすめの本を紹介するサイトです。Qiitaの投稿記事に紹介されている本の情報をまとめて紹介するサイト「Tekubu」（テクブ）。プログラミングに関する知識を記録・共有するためのサービスQiitaに投稿している記事数をカウントしておすすめの本をご紹介します。" %>

<div class="p-about">
	<div class="c-box p-about__item">
		<h1 class="c-headline">Tekubu（テクブ）とは？</h1>
		<p class="c-text--midium">Tekubu（テクブ）とは、エンジニアにおすすめの本を紹介するサイトです。プログラミングの本を探すとき種類が多すぎて選びきれない。他の先輩プログラマーや先輩エンジニアの方からおすすめしてほしいけど、周りにいない。そういった悩みを解消するためにプログラミングに関する知識を記録・共有サイトのQiitaさんで紹介されている本の記事数をカウントしてランキング形式で紹介しています。</p>
	</div>

	<div class="c-box p-about__item">
		<h2 class="c-headline">お知らせ</h2>
		<p class="c-text--midium">「Tekubu（テクブ）」はamazon.co.jpを宣言しリンクすることによってサイトが紹介料を獲得できる手段を提供することを目的に設定されたアフィリエト宣言プログラムである、Amazonアソシエイト・プログラムの参加者です。</p>
	</div>

	<div class="c-box p-about__item">
		<h2 class="c-headline">免責事項</h2>
		<p class="c-text--midium">できる限り正確な情報を掲載するよう心がけておりますが、必ずしも正確性を保証するものではありません。<br>
			紹介した商品のご購入や各種サービスを利用になる場合、ご覧になった貴方の責任にてお願い致します。<br>
		当サイトを利用することで発生した、いかなる結果にも一切責任を負いかねます。</p>
	</div>

	<div class="c-box p-about__item">
		<h2 class="c-headline">ご要望・お問い合わせ</h2>
		<p class="c-text--midium">ご要望・お問い合わせなどありましたら、公式TwitterアカウントへDMをお送りください。<br>メールでのお問合わせの場合は tekubu.net@gmail.com へお願いします。</p>
		<div class="c-button">
			<a href="https://twitter.com/Tekubu_net" target="_blank">公式Twitter</a>
		</div>
	</div>
</div>

tekubu/app/views/home/index.html.erb
<% if @books.present? %>
<% @books.each do |book| %>
<article class="p-article c-box">
	<div class="c-text--small c-box__id">POST ID&nbsp;/&nbsp;<%= book.id %></div>
	<h2 class="c-box__title">
		<a href="<%= book.detailpageurl %>" target="_blank"><%= book.title %></a>
	</h2>

	<div class="c-box__content">
		<div class="c-box__image">
			<img src="<%= book.image %>" alt="<%= book.title %>">
		</div>
		<dl class="c-box__table">
			<% if book.author.present? %>
			<dt class="c-box__table__headline">著者</dt>
			<dd class="c-box__table__data"><%= book.author %></dd>
			<% end %>
			<% if book.publicationdate.present? %>
			<dt class="c-box__table__headline">発売日</dt>
			<dd class="c-box__table__data"><%= book.publicationdate %></dd>
			<% end %>
			<% if book.language.present? %>
			<dt class="c-box__table__headline">言語</dt>
			<dd class="c-box__table__data"><%= book.language %></dd>
			<% end %>
		</dl>
	</div>

	<% if book.content.present? %>
	<p class="c-box__text">
		<%= truncate(book.content, length: 120) %>
	</p>
	<% end %>

	<div class="c-button--sns js-sharebtn">
		<div class="c-button__sns__text"><i class="fab fa-twitter"></i> みんなにオススメする</div>
		<p class="c-button__sns__title"><%= book.title %></p>
		<p class="c-button__sns__link"><%= url_for(book) %></p>
	</div>

	<div class="c-box__quote">
		<h2 class="c-box__quote__title">掲載されているQiita記事（<%= book.dictionary.count %> 件）</h2>
		<ul class="c-box__quote__list">
			<% if book.dictionary.size >= 5 %>

			<% book.dictionary.first(5).each do |item| %>
			<li>
				<a href="<%= item.url %>" target="_blank"><%= item.name %></a>
			</li>
			<% end %>
			<%= link_to "もっと見る", book %>
			<% else %>
			<% book.dictionary.each do |item| %>
			<li>
				<a href="<%= item.url %>" target="_blank"><%= item.name %></a>
			</li>
			<% end %>

			<% end %>
		</ul>
	</div>

	<ul class="p-article__bottom c-text--midium">
		<li class="c-button--primary">
			<a href="<%= book.detailpageurl %>" target="_blank">Amazon</a>
		</li>
		<li class="c-button--gray">
			<%= link_to "詳細", book %>
		</li>
	</ul>

</article>
<% end %>
<%= will_paginate @books, :class => 'p-pager' %>
<% else %>
<p>記事がありません。</p>
<% end %>

tekubu/app/views/home/show.html.erb
<article class="p-article c-talk--right">
	<p class="c-talk__name"><%= @book.event_id %></p>
</article>


<ul class="p-sns">
	<!-- <li class="c-sns--facebook"><i class="fa fa-facebook" aria-hidden="true"></i>facebookボタン</li> -->
	<li class="c-sns--twitter">
			<i class="fa fa-twitter" aria-hidden="true"></i>twitterボタン
		</a>
	</li>
</ul>

tekubu/app/views/layouts/error.html.erb
<!DOCTYPE html>
<html>
<head prefix="og: http://ogp.me/ns# fb: http://www.facebook.com/2008/fbml">
  <%= display_meta_tags(default_meta_tags) %>
  <%= csrf_meta_tags %>
  <%= render "shared/head" %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <meta name="google-site-verification" content="Oz3Labm5uZvIz7Sh9CUW0Wec58KfFBfDC9H7NTLbCW4" />
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-50448281-4"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-50448281-4');
  </script>

</head>
<body>
  <%= render "shared/header" %>

  <div class="p-content">
    <div class="p-content__inner">
      <%= yield %>

      <div class="c-button">
        <%= link_to "トップページに戻る", root_path %>
      </div>
    </div>
  </div>

  <%= render "shared/footer" %>
</body>
</html>

tekubu/app/views/shared/_errors.html.erb
<% if obj.errors.present? %>
<div id="errors">
<h3>エラーがあります。</h3>
<ul>
  <% obj.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
  <% end %>
</ul>
</div>
<% end %>

tekubu/app/views/shared/_footer.html.erb
<div class="p-footer">
	<ul>
		<li>
			<a href="https://twitter.com/Tekubu_net" target="_blank">公式Twitter</a>
		</li>
		<li>
			<a href="/about">このサイトについて</a>
		</li>
	</ul>
	<p class="p-footer__copy">
		Copyright (C) 2018 <%= link_to "Tekubu", root_path %>
	</p>
</div>

tekubu/app/views/shared/_header.html.erb
<header class="p-header">
	<div class="p-header__inner">

		<% if current_page?(root_path) %>

		<h1 class="p-header__logo">
			<%= link_to root_path do %>
			<span class="p-header__logo__text">Tekubu</span>
			<span class="p-header__logo__cap c-text--small">&ensp;-エンジニア・プログラマーにおすすめの本を紹介するサイト-</span>
			<% end %>
		</h1>
		<% else	%>
		<p class="p-header__logo">
			<%= link_to root_path do %>
			<span class="p-header__logo__text">Tekubu</span>
			<span class="p-header__logo__cap c-text--small">&ensp;-エンジニア・プログラマーにおすすめの本を紹介するサイト-</span>
			<% end %>
		</p>
		<% end %>

		<div class="p-header__menu__btn">
			<i class="fas fa-list-ul"></i>
		</div>
		<ul class="p-header__menu">
			<li>
				<%= link_to "TOP", root_path %>
			</li>
			<li>
				<%= link_to "Tekubu（テクブ）について", about_path %>
			</li>
			<li>
				<a href="https://twitter.com/Tekubu_net" target="_blank">公式Twitter</a>
			</li>
		</ul>

		<div class="p-header__count">
			掲載書籍数&nbsp;/&nbsp;<%= Book.where.not(title: nil).count %>
		</div>
	</div>

<!-- <div class="p-header__item">
	<%#= link_to "イベント一覧", events_path %>
</div>

<div class="p-header__item">
	<%#= link_to "book一覧", books_path %>
</div>
 -->
</header>